# Generated by Django 3.0.6 on 2020-05-29 12:24

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='post',
            field=models.TextField(default=datetime.datetime(2020, 5, 29, 12, 24, 33, 641458, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
