# Generated by Django 3.0.6 on 2020-05-29 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_articles_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.TextField(default=datetime.datetime(2020, 5, 29, 13, 56, 38, 879464, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
