# Generated by Django 3.0.6 on 2020-05-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200530_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='createdBy',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
