# Generated by Django 3.0.6 on 2020-05-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_createdby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-date']},
        ),
    ]
