# Generated by Django 3.0.6 on 2020-05-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
