# Generated by Django 3.0.6 on 2020-05-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200531_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
